mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  type-aliases-package: fr.cph.stock.entities
server:
  error:
    whitelabel:
      enabled: false
app:
  name: Stock Tracker
  db:
    driver: com.mysql.cj.jdbc.Driver
  report:
      ireport: report.jrxml
